### ISSUE TITLE
uxcore-tinymce单独使用问题

### ISSUE THREAD

**Issue by xueyuchen** [uxcore/uxcore-tinymce#11]
插件貌似是通过cdn加载的
加载时出现问题

```
Failed to load: //g.alicdn.com/platform/c/tinymce/4.3.12/plugins/{xxxx}/plugin.js
```

**Comment by eternalsky** [comment]
请看下 https://github.com/uxcore/uxcore-tinymce/blob/master/index.html 里面引用的 tinymce 地址，放到 cdn 上是为了保证加载速度，请具体提供一下不能加载的插件。

**Comment by zeybar** [comment]
我也出现了这个问题，提示**tinymce is not defined**
地址加载不出来

**Comment by eternalsky** [comment]
@zeybar tinymce is not defined 是因为没有引入 tinymce.js 吧~ 这个组件只是 tinymce 的 React 封装，tinymce 是需要自己引入的~

可以看下这里：https://github.com/uxcore/uxcore-tinymce/blob/master/index.html#L17
