### ISSUE TITLE
把富文本放在弹框的表单中出现小问题

### ISSUE THREAD

**Issue by chzng** [uxcore/uxcore-tinymce#12]
场景：点击新增按钮，弹出Dialog组件，Dialog包含Form表单，Form表单有富文本组件EditorFormField，在富文本组件输入内容提交保存后，第一点击编辑按钮，同时弹出Dialog，同时向后端发出请求获取刚才提交的富文本内容(后端返回正确且内容)，此时的第一次弹框富文本有内容显示，关闭弹框。第二次点击编辑弹框（弹框的同时向后端请求且返回的数据正确有内容），**问题出现了：此时弹框表单的富文本内容就不显示了**，此后关闭弹框，再点击编辑出现的弹框表单内的富文本都没有内容

**Comment by eternalsky** [comment]
场景有点复杂，可以提供一个复现 demo，或者尽量降低一些场景复杂度吗，我们推荐使用 codepen http://codepen.io/eternalsky/pen/qZwNVL

**Comment by eternalsky** [comment]
reopen it if you have more comments
