### ISSUE TITLE
Recommended way to integrate component?

### ISSUE THREAD

**Issue by stevenarnold** [uxcore/uxcore-tinymce#16]
Is there a recommended way to integrate this component with an existing React project? Any guidance would be appreciated. I could guess, but I thought there might be a command or similar approach that would neatly package this for third-party usage.

**Comment by eternalsky** [comment]
yes, you can follow the full package install guide https://github.com/uxcore/uxcore#import-component-as-required

**Comment by stevenarnold** [comment]
Thank you all for doing this great work under a permissive license. We are probably going to get deep into the weeds on this project and if we do anything useful in your components, I’d like to contribute them upstream, at least for your review. If we have an idea of something we’d like to do, like a feature to add, is it best to open an issue to discuss with you first? I would imagine so, given your intimate knowledge of your code.

As one example, I’d like to upgrade TinyMCE to the latest version. I don’t know the scope of this task, but in principle it would be nice to do. What are your thoughts on the best way for us to coordinate?

**Comment by eternalsky** [comment]
All efforts to enhance the component are very wellcomed. You can check the [Contributing document](https://github.com/uxcore/uxcore/blob/master/CONTRIBUTING.md#submitting-a-pull-request) to see how to coordinate with us.

**Comment by eternalsky** [comment]
outdated
