### ISSUE TITLE
图片上传

### ISSUE THREAD

**Issue by twinkle77** [uxcore/uxcore-tinymce#19]
图片需要上传到COS,返回的是url，请问怎么解决这个问题？

**Comment by eternalsky** [comment]
没明白你的具体诉求是什么

**Comment by twinkle77** [comment]
@eternalsky 首先感谢你的回答

```javascript
uploadConfig: {
    "inputName": "imageUploadInput",//上传的file input的name属性，默认file
    "actionUrl": "http://example.com/upload.json",//数据提交后端处理接口，需要返回JSON格式数据
    "formatResult": function(response){ //数据返回结构化，optional，供老接口兼容使用，return的Object是plugin预期的结构
        return {
            content: {
                "name": response.result.name,
                "downloarUrl": response.result.url
            }
        };
    },
    "errorCallback": function(){ //自定义的错误回调，optional，不设置会直接alert错误
        console.log('errorCallback', arguments);
    },
    "progressCallback": function(){ //自定义的上传进度回调，optional，不设置不显示进度
        console.log('progressCallback', arguments);
    }
}
```
我的需求是，点击富文本组件的**上传图片**按钮，选择图片后不是需要上传才能显示在**内容框**里面吗？

但图片上传配置项，好像没有提供类似的回调方法。。。

小菜鸟一只。感谢回答

**Comment by eternalsky** [comment]
@sinner77 你引用的部分都是图片上传的配置项，`没有类似的回调方法` 指的是？

**Comment by twinkle77** [comment]
@eternalsky 
我项目中上传图片用的是腾讯云的对象存储。 
比如我在react里面调用 cos.uploadFile(图片文件对象, ....)就能返回图片的src
但是不知道怎么将这个图片src用到这个富文本组件中

**Comment by twinkle77** [comment]
比如我点击富文本组件的*上传图片*btn, 选择本地的图片后, 点击*提交*，富文本不是应该输出
```javascript
<img src="http://www.xxxx" />
```
吗？
感谢回答

**Comment by eternalsky** [comment]
@sinner77 我们提供的插件是自己实现的上传，因此我们需要用户提供的就是一个用于上传的 url 地址，我们希望这个 url 在上传后能够返回用于展示的图片地址，我们拿到这个地址，插入到富文本当中。因此用 `cos.uploadFile` 这种自己实现上传的话，可能就没法用我们提供的插件了，但是你可以参考 tinymce 的文档，自己实现一个插件，我们这个项目只是对 Tinymce 的一个 React 封装。

**Comment by twinkle77** [comment]
@eternalsky 懂了。谢谢你

**Comment by lf75152798** [comment]
在dialog中 点击图片上传，没有反应。未出现选择图片界面

**Comment by eternalsky** [comment]
@lf75152798
