### ISSUE TITLE
uploadConfig配置求解

### ISSUE THREAD

**Issue by jiankian** [uxcore/uxcore-tinymce#20]
图片上传接口，如何添加headers参数，看了半天没有这个例子。上传方法是POST吗

**Comment by eternalsky** [comment]
https://g.alicdn.com/uxcore/uxcore-lib/tinymce/4.2.5/plugins/upload/plugin.min.js

这是我们正在使用的插件，是 post 上传，目前不支持设置特殊的 headers。
