### ISSUE TITLE
onchange能优化下吗？

### ISSUE THREAD

**Issue by huyawei** [uxcore/uxcore-tinymce#22]
第一次输入会触发onchange
之后输出不触发
点击回车触发onchange
上传图片触发onchange
能不能输入以及插入操作就触发onchange
如果搭配 onkeyup的话经常会触发多次，不是很合适

**Comment by eternalsky** [comment]
tinymce 本身的问题，https://github.com/uxcore/uxcore-tinymce/issues/1
